---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "Include andrelohmann.root_colored_prompt"
      include_role:
        name: "andrelohmann.root_colored_prompt"
...
