---
name: Molecule

on:
  push:
    branches:
      # some older repositories still use master, all newer ones use main
      - master
      - main
      - "feature/*"
  pull_request:
    branches:
      # some older repositories still use master, all newer ones use main
      - master
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      # - name: Run ansible-lint
      #   # replace `main` with any valid ref, or tags like `v6`
      #   uses: ansible/ansible-lint-action@main
      #   # optional:
      #   # with:
      #   #   path: "playbooks/"  # <-- only one value is allowed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint
      - name: Lint playbook
        run: |
          echo ${{ github.repository }}
          cd ${{ github.repository }}
          pwd
          ls -al
          yamllint --version
          yamllint .
          ansible-lint .

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: -d docker
          molecule_working_dir: andrelohmann/ansible-role-root_colored_prompt
        env:
          ANSIBLE_FORCE_COLOR: '1'
...
